#!/bin/bash
#PBS -N thwaites
#PBS -q long
#PBS -W group_list=s5692
#PBS -l select=22:ncpus=28:model=bro
#PBS -l walltime=100:00:00
#PBS -j oe
#PBS -m abe
#PBS -l site=needed=/home1+/home3+/home4+/nobackupp17

module load comp-intel/2020.4.304
module load mpi-hpe/mpt.2.28_25Apr23_rhel87
module load szip/2.1.1
module load hdf4/4.2.12 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt

export RUN_DIR=/nobackupp11/mpoinell/thwaites/run_thwaites01c/

cd $RUN_DIR
mpiexec -np 616 ./mitgcmuv
