#!/bin/bash
#PBS -N thwates
#PBS -q long
#PBS -W group_list=s5692
#PBS -l select=1:ncpus=1:model=ivy
#PBS -l walltime=00:05:00
#PBS -j oe
#PBS -m abe
#PBS -l site=needed=/home1+/home3+/home4+/nobackupp17

module load comp-intel/2020.4.304
module load mpi-hpe/mpt.2.25
module load hdf4/4.2.12 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt

export RUN_DIR=/nobackupp11/mpoinell/ecco_polar_regional/Amundsen_Bellinghausen/Poinelli2024/run

cd $RUN_DIR
mpiexec -np 1 ./mitgcmuv
